"""Build the browser-only copy of the app into docs/app/.

    python tools/build_static.py

Why a script rather than a second copy of the app: the page in docs/app/ is
the same page. Its map, its heat radar, its legend and its reach colours all
come from the *same* static/js/app.js and static/css/style.css the Flask app
serves — copied here byte for byte, never edited. The only things this build
adds are a fetch shim that answers app.js's four `/api/...` calls in the
browser (tools/static_src/js/static-api.js), a port of the reachability
Dijkstra (static-reach.js), and the graph itself, inlined.

Inlined as a `.js` file rather than fetched as a `.json`, deliberately: a
`fetch()` of a relative JSON URL is blocked by the file:// origin rules, so a
JSON bundle would work on GitHub Pages and fail the moment somebody
double-clicked index.html. A `<script src>` has no such restriction, so the
same directory works both ways.

What this build cannot do is plan a trip. itinerary.py is 576 lines against a
timetable index built from TTC's static GTFS, and it answers "what time do
you arrive" — a claim that is right or it is worthless. Approximating it
would print departures nobody can catch, so the trip planner is switched off
here and the page says so. The reachability search, which is the headline
feature, is ported in full.

What it checks before writing anything:

  * every mode in the graph has a modelled wait, and every line has a
    recorded mode — the JS falls back the same way the Python does, but a
    fallback that fires is a missing entry, not a design;
  * `realtime.impact_on` is 0.0 for every line under the static model, which
    is the assumption that lets the ported search skip closure handling
    entirely;
  * the ported boarding-wait rule, re-implemented here from the data the
    bundle actually ships, agrees with `realtime.Conditions.boarding_wait`
    for all 516 stops. That is the rule that was wrong on the server once
    (a line's wait must come from the line's mode, not the node's), and this
    is what stops the browser build reintroducing it.
"""

import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

OUT = os.path.join(ROOT, "docs", "app")
SRC = os.path.join(ROOT, "tools", "static_src")

REPO = "https://github.com/luke-zhang-cs-py/Toronto-Transit-Distance-Matrix"

# Copied unchanged from the Flask app, so both builds are running the same
# code. when.js is *not* here: it is the "leave now / leave at" control, and
# it exists only to feed the trip planner this build does not have.
SHARED_JS = ["app.js", "here.js"]
STATIC_JS = ["static-reach.js", "static-api.js", "static-ui.js"]

# The order the page loads them in. static-api must be before app.js, which
# calls loadNetwork() and loadLiveStatus() as it finishes; static-ui must be
# after it, because it replaces functions app.js defines.
SCRIPT_ORDER = ["js/network-data.js", "js/static-reach.js", "js/static-api.js",
                "js/app.js", "js/here.js", "js/static-ui.js"]

BANNER = "/* Generated by tools/build_static.py -- edit %s instead. */\n"


def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read()


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def replace_once(text, old, new, what):
    """A substitution that fails loudly if the source moved.

    Every edit below is a string match against templates/index.html. A miss
    is silent by default -- the page builds, looks nearly right, and is
    missing the one sentence that says it is a model. So each one is counted.
    """
    count = text.count(old)
    if count != 1:
        raise SystemExit(
            "build_static: could not %s -- expected exactly one match in "
            "templates/index.html, found %d. The template has moved; fix "
            "the anchor in tools/build_static.py.\n  looking for: %r"
            % (what, count, old[:120]))
    return text.replace(old, new)


# ---------------------------------------------------------------------------
# The graph
# ---------------------------------------------------------------------------
def collect_graph():
    """Everything the ported search reads, and the checks that it is enough."""
    from feeds import realtime
    from network import nodes, adj, WALK_KMH, WAIT_BY_MODE, DEFAULT_WAIT_MIN
    from network import lines_at, mode_of_line
    from network.graph import LINE_MODES, TRANSFER

    lines = sorted({edge["line"] for edges in adj.values() for edge in edges})
    modes = sorted({node["mode"] for node in nodes.values()})

    missing_mode = [mode for mode in modes if mode not in WAIT_BY_MODE]
    if missing_mode:
        raise SystemExit(
            "build_static: no modelled wait for %s. The ported search would "
            "fall back to DEFAULT_WAIT_MIN and quietly disagree with the "
            "server. Add it to network/graph.py WAIT_BY_MODE."
            % ", ".join(missing_mode))

    # 'Transfer' is not a service anybody boards, so it has no mode and
    # lines_at() drops it; anything else without one is an add_edge that
    # forgot to say which agency runs it.
    unrecorded = [line for line in lines
                  if line != "Transfer" and mode_of_line(line) is None]
    if unrecorded:
        raise SystemExit(
            "build_static: these lines have no recorded mode, so their wait "
            "would come from whichever node they were boarded at: %s"
            % ", ".join(unrecorded))

    conditions = realtime.Conditions.static()
    surcharged = [line for line in lines if conditions.impact_on(line) != 0.0]
    if surcharged:
        raise SystemExit(
            "build_static: the static model now prices or closes %s. "
            "static-reach.js skips closure handling because it never did; "
            "port realtime.impact_on before shipping this." % surcharged)

    check_boarding_waits(nodes, adj, conditions, lines_at,
                         LINE_MODES, WAIT_BY_MODE, DEFAULT_WAIT_MIN)

    return {
        "walkKmh": WALK_KMH,
        "transferMinutes": TRANSFER,
        "waitByMode": dict(WAIT_BY_MODE),
        "defaultWaitMin": DEFAULT_WAIT_MIN,
        "lineModes": dict(LINE_MODES),
        "nodes": {nid: {"name": n["name"], "lat": n["lat"], "lon": n["lon"],
                        "mode": n["mode"]}
                  for nid, n in nodes.items()},
        "adj": {nid: [[e["to"], e["min"], e["line"]] for e in edges]
                for nid, edges in adj.items()},
    }


def check_boarding_waits(nodes, adj, conditions, lines_at, line_modes,
                         wait_by_mode, default_wait):
    """The ported rule, run against the real one, for every stop.

    This is a transcription of what static-reach.js does, using only the
    fields the bundle carries -- so if the JS and the Python ever part
    company, they part company here first and the build stops.
    """
    wrong = []
    for nid, node in nodes.items():
        best = wait_by_mode.get(node["mode"], default_wait)
        for line in lines_at(nid):
            line_mode = line_modes.get(line) or node["mode"]
            value = wait_by_mode.get(line_mode, default_wait)
            if value < best:
                best = value
        real, _measured = conditions.boarding_wait(lines_at(nid), node["mode"])
        if best != real:
            wrong.append("%s: port says %s, realtime says %s" % (nid, best, real))
    if wrong:
        raise SystemExit(
            "build_static: the ported boarding-wait rule disagrees with "
            "realtime.Conditions.boarding_wait:\n  " + "\n  ".join(wrong[:20]))


def data_file(graph):
    """The graph as one `const`, with its layout written down beside it.

    Compact arrays for the adjacency -- `{"to":..,"min":..,"line":..}` per
    edge is the same information at three times the size, and there are
    1,236 of them. The nodes stay as objects because app.js reads them
    straight out of the /api/network response by name.
    """
    # Insertion order, not sorted. `nodes` and `adj` are dicts on both sides,
    # and app.py's /api/network walks them in the order the network modules
    # built them -- so sorting the keys here quietly reversed which end of
    # each undirected edge the browser drew first. Same picture, different
    # bytes, and no longer the same answer as the server's.
    body = json.dumps(graph, sort_keys=False, separators=(",", ":"))
    return (
        "/* Generated by tools/build_static.py from the `network` package --\n"
        " * do not edit. Rebuild with: python tools/build_static.py\n"
        " *\n"
        " * The whole transit graph, inlined as a script rather than fetched\n"
        " * as JSON so that opening index.html from the filesystem works as\n"
        " * well as serving it: a relative fetch() is blocked by the file://\n"
        " * origin rules and a <script src> is not.\n"
        " *\n"
        " *   nodes     id -> {name, lat, lon, mode}\n"
        " *   adj       id -> [[to, minutes, line], ...]   (both directions)\n"
        " *   lineModes line name -> the mode that runs it, which is what\n"
        " *             decides its wait. Not the node's mode: Union is a\n"
        " *             subway node and a GO train boarded there waits 20\n"
        " *             minutes, not 4.\n"
        " *   waitByMode / defaultWaitMin / walkKmh  network/graph.py\n"
        " */\n"
        "const NETWORK_DATA = %s;\n" % body)


# ---------------------------------------------------------------------------
# The page
# ---------------------------------------------------------------------------
def page(template):
    text = template

    text = replace_once(
        text,
        "<title>Toronto Transit Reach (Python)</title>",
        "<title>Toronto Transit Reach (browser build)</title>",
        "retitle the page")

    text = replace_once(
        text,
        "<link rel=\"stylesheet\" href=\"{{ url_for('static', "
        "filename='css/style.css') }}\">",
        '<link rel="stylesheet" href="css/style.css">\n'
        '<link rel="stylesheet" href="css/static.css">',
        "point the stylesheet at the copied CSS")

    text = replace_once(
        text,
        "<h1>Toronto Transit Reach<em>Python backend</em></h1>",
        "<h1>Toronto Transit Reach<em>browser build</em></h1>",
        "relabel the heading")

    text = replace_once(
        text,
        """<div class="sub">Classic OpenStreetMap tiles, no API key. Every travel time, route, and
      heat-radar point is computed by a Python routing engine over the full TTC + YRT + MiWay
      network. Click once for a start point, click again for a destination.</div>""",
        """<div class="sub">Classic OpenStreetMap tiles, no API key. Click anywhere on the map:
      every stop you can reach is shaded by how long it takes, over the full TTC + YRT + MiWay
      network. The search runs in your browser.</div>
    <div class="staticBanner">
      <b>This is the browser-only build.</b> There is no server: the whole graph is inlined in
      the page and the reachability search — a port of the same Dijkstra in
      <code>routing.py</code> — runs in JavaScript. Every wait is therefore <b>modelled</b>
      (half the typical headway for the mode running the line), not measured: GTFS-realtime
      needs a backend to fetch it, so live waits and service closures are not in this build,
      and neither is trip planning.
      <a href="%s">Run the Flask app for the live-data version →</a>
    </div>""" % REPO,
        "rewrite the standfirst and add the build banner")

    text = trip_card(text)
    text = replace_once(
        text,
        """<footer>Fixed schematic network model (TTC subway/streetcar + YRT/Viva + MiWay + highway
    corridor hubs) with typical dwell/wait/transfer times — not a live feed. All routing runs
    in the Python backend; the browser only draws the results.</footer>""",
        """<footer>Fixed schematic network model (TTC subway/streetcar + YRT/Viva + MiWay + highway
    corridor hubs) with typical dwell/wait/transfer times — not a live feed. In this build the
    routing runs in the browser, over a copy of the graph generated from the Python
    <code>network</code> package by <code>tools/build_static.py</code>; the Flask app in the
    repository is the same page with a live feed and a trip planner behind it.</footer>""",
        "rewrite the footer")

    scripts = "\n".join('<script src="%s"></script>' % name
                        for name in SCRIPT_ORDER)
    text = replace_once(
        text,
        """<script src="{{ url_for('static', filename='js/app.js') }}"></script>
  <!-- After app.js: both read map, setOrigin and planTrip from it. -->
  <script src="{{ url_for('static', filename='js/when.js') }}"></script>
  <script src="{{ url_for('static', filename='js/here.js') }}"></script>""",
        "<!-- Order matters: static-api.js installs the fetch shim before\n"
        "     app.js runs and calls it; static-ui.js replaces functions\n"
        "     app.js defines, so it goes last. when.js is absent -- it is the\n"
        "     departure-time control for the trip planner. -->\n"
        + scripts,
        "rewrite the script tags")

    left = re.findall(r"\{\{.*?\}\}|\{%.*?%\}", text)
    if left:
        raise SystemExit("build_static: unresolved Jinja left in the page: %r" % left)
    return text


def trip_card(text):
    """Swap the trip planner for a note saying where it went.

    The card itself stays in the markup, emptied and still hidden: app.js
    binds #newTripBtn at load and reads #tripCard in setOrigin, and a build
    that deletes them throws a TypeError before the map has drawn. What
    changes is that nothing ever shows it -- static-ui.js sends the second
    click back to setOrigin -- and that the note beside it is visible from
    the start rather than after a trip nobody can plan.
    """
    start = text.index('      <div class="section" id="tripCard"')
    end = text.index('      <div class="section" id="filterCard">')
    if not 0 < start < end:
        raise SystemExit("build_static: could not find the trip card in the template")

    note = """      <!-- The trip planner is not in this build. itinerary.py plans against a
           timetable index built from TTC's static GTFS, and it answers "what time
           do you arrive" -- a claim that is either right or worthless. A partial
           port would print departures nobody can catch, so it is switched off and
           says so. -->
      <div class="section" id="staticNote">
        <h2>Browser-only build</h2>
        <div class="hint"><b>Trip planning needs the local Flask app</b> — see the
          <a href="%s#run-it">README</a>. This build answers the reach
          question only: click anywhere and every stop is shaded by how long it takes
          to get there, computed here in the page.</div>
        <div class="stat"><span>Data</span><b id="liveBadge">modelled</b></div>
      </div>

      <div class="section" id="tripCard" style="display:none;">
        <div id="optionList"></div>
        <div id="tripDetail"></div>
        <button class="secondary" id="newTripBtn">Start a new trip</button>
      </div>

""" % REPO
    return text[:start] + note + text[end:]


# ---------------------------------------------------------------------------
def prune(kept):
    """Delete anything left in docs/app/ from an older build.

    Without this a renamed file lives on and is still loaded, which is the
    one failure mode a generated directory has that a hand-written one does
    not.
    """
    for here, dirs, names in os.walk(OUT):
        for name in names:
            path = os.path.join(here, name)
            if os.path.relpath(path, OUT).replace("\\", "/") not in kept:
                os.remove(path)
                print("  removed stale %s" % os.path.relpath(path, OUT))


def main():
    graph = collect_graph()
    written = {}

    written["js/network-data.js"] = data_file(graph)

    for name in SHARED_JS:
        written["js/" + name] = (BANNER % ("static/js/" + name)
                                 + read(os.path.join(ROOT, "static", "js", name)))
    for name in STATIC_JS:
        written["js/" + name] = read(os.path.join(SRC, "js", name))

    written["css/style.css"] = (BANNER % "static/css/style.css"
                                + read(os.path.join(ROOT, "static", "css", "style.css")))
    written["css/static.css"] = read(os.path.join(SRC, "css", "static.css"))
    written["index.html"] = page(read(os.path.join(ROOT, "templates", "index.html")))

    for name, body in sorted(written.items()):
        write(os.path.join(OUT, name.replace("/", os.sep)), body)
    prune(set(written))

    total = sum(len(body.encode("utf-8")) for body in written.values())
    print("  %d stops, %d directed edges, %d lines"
          % (len(graph["nodes"]),
             sum(len(v) for v in graph["adj"].values()),
             len(graph["lineModes"])))
    print("  wrote %d files to docs/app (%.0f KB, %.0f KB of it the graph)"
          % (len(written), total / 1024.0,
             len(written["js/network-data.js"].encode("utf-8")) / 1024.0))


if __name__ == "__main__":
    main()
